### ISSUE TITLE
lonekorean/highlight-within-textarea 

### ISSUE THREAD

**Issue by sharvarilimbkar** [lonekorean/highlight-within-textarea#1]
i am using lonekorean/highlight-within-textarea in my laravel project 
var  dummystr=' '; // gobal varible created in my javascript file 
and in 
 function onInput(input) {
    // do stuff, return something
    return dummystr;
}
but when i return this gobal varible using this that  time it gives
uncaught exception: Unrecognized payload type returned from onInput callback.
such exception ...
how to solve this one
rpl fast

**Comment by lonekorean** [comment]
The plugin doesn't (currently) support string as a payload type, but you can do this instead:

``` javascript
return new RegExp(dummystr, 'g');
```

The 'g' makes it match all occurrences instead of just the first, use it or remove it as you need.

Also, since it's a regex, be sure to double escape special characters. Use `'\\.'` to match `'.'` for example.

I'll probably add string as a supported payload type in the future. Seems reasonable.

**Comment by elcilerdenbiri** [comment]
I had similar issue!

**Highlighting multiple/different characters/words by clicking different buttons BUT ...!**

BUT ... I want to store old button id s in a global string and use/highlight every letter in that string dynamically(User clicks buttons and the js code push pop button id s to/from string and highlight all characters in that updated string) !
