### ISSUE TITLE
Trigger on button click

### ISSUE THREAD

**Issue by nferrari** [lonekorean/highlight-within-textarea#3]
Hi,

The payload is currently triggered every time the input changes. I'd like to call a remote webservice, thus it will be preferable to trigger when the user decides it, for example by clicking on a button.

What do you think?

Thank you.

**Comment by lonekorean** [comment]
Hi, sorry for the delayed response. Sounds reasonable. I'll keep this open and revisit when I have time. Thanks!

**Comment by lonekorean** [comment]
So, I know it's been over a year, and you've probably long since moved on, but wanted to drop a note that manual updating is possible now:

```javascript
$('.my-textarea').highlightWithinTextarea('update');
```

So your custom highlight function could have logic to check an `areResultsReady` flag (or whatever). If no, return `false` (no highlighting). If yes, return the results from the web service. And you can manually call the above "update" function when you know `areResultsReady` is `true`.
